Merge main into refactor
legend-exp/pygama pull request #253
Opened 2022-04-20 04:40 UTC by jasondet

2022-04-20 04:41 UTC, jasondet commented
@gipert I'm trying to merge recent main changes into refactor but there were some conflicts in docs. I think I resolved them all but can you check them?

2022-04-20 08:28 UTC, gipert requested changes

2022-04-20 08:28 UTC, gipert commented on docs/source/conf.py
> +import os
This import is not needed

2022-04-20 08:28 UTC, gipert commented on docs/source/index.rst
> +* :ref:`search`
Remove these added lines please

2022-04-21 03:21 UTC, jasondet commented on docs/source/conf.py
> +import os
done

2022-04-21 03:21 UTC, jasondet commented on docs/source/index.rst
> +* :ref:`search`
done

2022-04-21 05:07 UTC, gipert approved these changes

2022-04-26 15:50 UTC, merged