Added discrete wavelet transform processor
legend-exp/pygama pull request #349
Opened 2022-08-19 00:12 UTC by esleon97

Before submitting a pull request, please make sure you've read and understood the pygama developer's guide: https://pygama.readthedocs.io/en/latest/developer.html. In particular, do not forget to:

- [ ] Conform to our **coding conventions**
- [ ] Update existing or add new **tests**
- [ ] Update existing or add new **documentation**
- [ ] Address any issue reported by GitHub checks

2022-08-19 09:44 UTC, gipert requested changes
Thanks a lot! I just left some suggestions about doctring styling.

2022-08-19 09:44 UTC, gipert commented on src/pygama/dsp/processors/dwt.py
> +    'args'. The output waveform dimension must be specified.
```suggestion
    This processor is composed of a factory function that is called using the
    ``init_args`` argument. The input and output waveforms are passed using
    ``args``. The output waveform dimension must be specified.
```

2022-08-19 09:44 UTC, gipert commented on src/pygama/dsp/processors/dwt.py
> +       The level of decompositions to be performed (1, 2, ...)
```suggestion
       The wavelet type for discrete convolution ``('haar', 'db1', ...)``
    level
       The level of decompositions to be performed ``(1, 2, ...)``
```

2022-08-19 09:44 UTC, gipert commented on src/pygama/dsp/processors/dwt.py
> +           obtained via pywt.Wavelet(wave_type).dec_len
```suggestion
           The approximate coefficients. The dimension of this array can be calculated
           by ``out_dim = wf_length/(filter_length^level)``, where ``filter_length`` can be
           obtained via ``pywt.Wavelet(wave_type).dec_len``.
```

2022-08-19 19:17 UTC, gipert approved these changes

2022-08-22 10:17 UTC, ggmarshall reviewed
Looks good, to conform with the other processors can you change it from wf_in/wf_out to w_in/w_out, do you want to add it to the init file also

2022-08-22 16:05 UTC, gipert commented
@esleon97 can you please update this according to https://github.com/legend-exp/pygama/pull/350?

2022-08-24 10:45 UTC, ggmarshall approved these changes

2022-08-24 10:46 UTC, ggmarshall commented
It seems the pre-commit removed the changes to the init file?

2022-08-24 11:29 UTC, gipert commented
You need to add the processor name to the `__all__` vector in `__init__.py`.

Another thing: `dwt()` is maybe a bit cryptic, why not `discrete_wavelet_transform()`? Or just `discrete_wavelet()`?

2022-09-14 15:22 UTC, jasondet commented
@gipert looks like everything is dying on this now. Was whatever is responsible for flake8 somehow updated under the hood? Anyway, I'll see if I can fix it...

2022-09-14 15:26 UTC, gipert commented
Not sure but looks like a new flake8 feature. Guess we can just add those decorators...

2022-09-14 15:41 UTC, jasondet commented
flake8 error is fixed in https://github.com/legend-exp/pygama/pull/373, will pull it in then merge this

2022-09-14 15:47 UTC, gipert commented
@jasondet can you also squash the commits before merging? I think we should do it always (if it makes sense) to keep our Git history more linear and clean.

2022-09-14 16:02 UTC, merged