Adding 'numpy.constants' parsing to 'dsp.processing_chain'
legend-exp/pygama pull request #365
Opened 2022-09-09 20:48 UTC by patgo25

This allows to use numpy constants (e.g.: `np.pi` , `np.e` , `np.inf`, `np.nan`) as arguments in the JSON file:

```
"calc1":{
            "function": "subtract",
            "module": "numpy",
            "args": ["foo", "5+2*(1+np.pi)*np.e", "calc1"]
        },
"calc2":{
            "function": "subtract",
            "module": "numpy",
            "args": ["foo", "np.inf", "calc2"]
}
"calc3":{
            "function": "subtract",
            "module": "numpy",
            "args": ["foo", "np.nan", "calc3"]
}
"calc4":{
            "function": "subtract",
            "module": "numpy",
            "args": ["foo", "5*np.pi*bar", "calc4"]
}
```
Added `tests\dsp\test_numpy_constants_parsing.py` and `tests\dsp\configs\numpy-parsing.json` for testing

Limitations:
```
"calcFAIL":{
            "function": "subtract",
            "module": "numpy",
            "args": ["foo", "np.inf*bar", "calcFAIL"]
        }
```
Raises exception since the sign of bar is not known. But who would do this anyhow?

This can be very useful for processors with default values e.g.

2022-09-10 18:59 UTC, iguinn requested changes
Hey Patrick,
This is a good idea for a feature to have! However, I have tried to move away from using regexs for parsing, and have tried to put as much parsing as possible in `_parse_expr`. This uses python's built in parsing module which makes it very flexible and maintainable. I've made changes to do it this way, and submitted a PR to your fork so you try it out. The way I've done it will grab any int/float attributes from an modules added to a list, which right now just includes numpy.

Also, `numexpr` is not a default python module, so adding this would create a new dependency for pygama, which would require a bit more discussion/review, so I've gotten rid of this.

Ian

2022-09-10 21:36 UTC, patgo25 commented
Thanks Ian.

I like your approach much more. 
The only divergence I see is that it doesn't support infinity arithmetic, but I guess nobody would do this anyhow ;)

I quickly change the tests and commit them here

2022-09-10 21:42 UTC, patgo25 commented
@iguinn Numexpr is already anyhow needed for pygama in `lgdo.Table.eval()` since the the pandas eval function depends on it (see [here](https://pandas.pydata.org/docs/user_guide/enhancingperf.html#expression-evaluation-via-eval) ) 

Maybe you also want to take a look at #363 which avoids  using pandas.eval(), to support `ArrayOfEqualSizedArrays` (which currently isn't)

2022-09-11 13:36 UTC, gipert commented
Seems to me all issues have been addressed here. I'll proceed (squashing and) merging.

2022-09-11 13:37 UTC, merged

2022-09-11 21:45 UTC, iguinn commented
Looks good! Also agree that numexpr is fine to use; I didn't realize that it had been added as an installation prereq already.